import { Injectable } from '@angular/core';
import { ListViewModel } from '../../view-models/core/list-types';

@Injectable({
  providedIn: 'root',
})
export class TimezoneService {
  timezones: ListViewModel[];

  constructor() {
    this.timezones = [
      { text: 'Samoa (GMT-11:00)', value: 'Pacific/Samoa' },
      { text: 'Pago Pago (GMT-11:00)', value: 'Pacific/Pago_Pago' },
      { text: 'Honolulu (GMT-10:00)', value: 'Pacific/Honolulu' },
      { text: 'Aleutian (GMT-09:00)', value: 'US/Aleutian' },
      { text: 'Juneau (GMT-08:00)', value: 'America/Juneau' },
      { text: 'BajaNorte (GMT-07:00)', value: 'Mexico/BajaNorte' },
      { text: 'Vancouver (GMT-07:00)', value: 'America/Vancouver' },
      { text: 'Phoenix (GMT-07:00)', value: 'America/Phoenix' },
      { text: 'Los Angeles (GMT-07:00)', value: 'America/Los_Angeles' },
      { text: 'Yellowknife (GMT-06:00)', value: 'America/Yellowknife' },
      { text: 'Managua (GMT-06:00)', value: 'America/Managua' },
      { text: 'Guatemala (GMT-06:00)', value: 'America/Guatemala' },
      { text: 'Denver (GMT-06:00)', value: 'America/Denver' },
      { text: 'Costa Rica (GMT-06:00)', value: 'America/Costa_Rica' },
      { text: 'Panama (GMT-05:00)', value: 'America/Panama' },
      { text: 'Mexico City (GMT-06:00)', value: 'America/Mexico_City' },
      { text: 'Lima (GMT-05:00)', value: 'America/Lima' },
      { text: 'Chicago (GMT-05:00)', value: 'America/Chicago' },
      { text: 'Bogota (GMT-05:00)', value: 'America/Bogota' },
      { text: 'Toronto (GMT-04:00)', value: 'America/Toronto' },
      { text: 'Santo Domingo (GMT-04:00)', value: 'America/Santo_Domingo' },
      { text: 'New York (GMT-04:00)', value: 'America/New_York' },
      { text: 'Montreal (GMT-04:00)', value: 'America/Montreal' },
      { text: 'Havana (GMT-04:00)', value: 'America/Havana' },
      { text: 'Detroit (GMT-04:00)', value: 'America/Detroit' },
      { text: 'Asuncion (GMT-04:00)', value: 'America/Asuncion' },
      { text: 'Sao Paulo (GMT-03:00)', value: 'America/Sao_Paulo' },
      { text: 'Santiago (GMT-03:00)', value: 'America/Santiago' },
      { text: 'Montevideo (GMT-03:00)', value: 'America/Montevideo' },
      { text: 'Buenos Aires (GMT-03:00)', value: 'America/Buenos_Aires' },
      { text: 'Bahia (GMT-03:00)', value: 'America/Bahia' },
      { text: 'Godthab (GMT-02:00)', value: 'America/Godthab' },
      { text: 'Abidjan (GMT+00:00)', value: 'Africa/Abidjan' },
      { text: 'Reykjavik (GMT+00:00)', value: 'Atlantic/Reykjavik' },
      { text: 'Greenwich (GMT+00:00)', value: 'Greenwich' },
      { text: 'Kinshasa (GMT+01:00)', value: 'Africa/Kinshasa' },
      { text: 'Lagos (GMT+01:00)', value: 'Africa/Lagos' },
      { text: 'Luanda (GMT+01:00)', value: 'Africa/Luanda' },
      { text: 'Tunis (GMT+01:00)', value: 'Africa/Tunis' },
      { text: 'Dublin (GMT+01:00)', value: 'Europe/Dublin' },
      { text: 'Lisbon (GMT+01:00)', value: 'Europe/Lisbon' },
      { text: 'London (GMT+01:00)', value: 'Europe/London' },
      { text: 'Cairo (GMT+02:00)', value: 'Africa/Cairo' },
      { text: 'Amsterdam (GMT+02:00)', value: 'Europe/Amsterdam' },
      { text: 'Belgrade (GMT+02:00)', value: 'Europe/Belgrade' },
      { text: 'Berlin (GMT+02:00)', value: 'Europe/Berlin' },
      { text: 'Bratislava (GMT+02:00)', value: 'Europe/Bratislava' },
      { text: 'Brussels (GMT+02:00)', value: 'Europe/Brussels' },
      { text: 'Budapest (GMT+02:00)', value: 'Europe/Budapest' },
      { text: 'Copenhagen (GMT+02:00)', value: 'Europe/Copenhagen' },
      { text: 'Ljubljana (GMT+02:00)', value: 'Europe/Ljubljana' },
      { text: 'Luxembourg (GMT+02:00)', value: 'Europe/Luxembourg' },
      { text: 'Madrid (GMT+02:00)', value: 'Europe/Madrid' },
      { text: 'Paris (GMT+02:00)', value: 'Europe/Paris' },
      { text: 'Prague (GMT+02:00)', value: 'Europe/Prague' },
      { text: 'Rome (GMT+02:00)', value: 'Europe/Rome' },
      { text: 'Stockholm (GMT+02:00)', value: 'Europe/Stockholm' },
      { text: 'Vienna (GMT+02:00)', value: 'Europe/Vienna' },
      { text: 'Warsaw (GMT+02:00)', value: 'Europe/Warsaw' },
      { text: 'Zagreb (GMT+02:00)', value: 'Europe/Zagreb' },
      { text: 'Zurich (GMT+02:00)', value: 'Europe/Zurich' },
      { text: 'Libya (GMT+02:00)', value: 'Libya' },
      { text: 'Addis Ababa (GMT+03:00)', value: 'Africa/Addis_Ababa' },
      { text: 'Khartoum (GMT+03:00)', value: 'Africa/Khartoum' },
      { text: 'Nairobi (GMT+03:00)', value: 'Africa/Nairobi' },
      { text: 'Amman (GMT+03:00)', value: 'Asia/Amman' },
      { text: 'Baghdad (GMT+03:00)', value: 'Asia/Baghdad' },
      { text: 'Beirut (GMT+03:00)', value: 'Asia/Beirut' },
      { text: 'Istanbul (GMT+03:00)', value: 'Asia/Istanbul' },
      { text: 'Jerusalem (GMT+03:00)', value: 'Asia/Jerusalem' },
      { text: 'Kuwait (GMT+03:00)', value: 'Asia/Kuwait' },
      { text: 'Riyadh (GMT+03:00)', value: 'Asia/Riyadh' },
      { text: 'Athens (GMT+03:00)', value: 'Europe/Athens' },
      { text: 'Helsinki (GMT+03:00)', value: 'Europe/Helsinki' },
      { text: 'Kiev (GMT+03:00)', value: 'Europe/Kiev' },
      { text: 'Moscow (GMT+03:00)', value: 'Europe/Moscow' },
      { text: 'Antananarivo (GMT+03:00)', value: 'Indian/Antananarivo' },
      { text: 'Tehran (GMT+03:30)', value: 'Asia/Tehran' },
      { text: 'Dubai (GMT+04:00)', value: 'Asia/Dubai' },
      { text: 'Samara (GMT+04:00)', value: 'Europe/Samara' },
      { text: 'Baku (GMT+04:00)', value: 'Asia/Baku' },
      { text: 'Aqtau (GMT+05:00)', value: 'Asia/Aqtau' },
      { text: 'Karachi (GMT+05:00)', value: 'Asia/Karachi' },
      { text: 'Yekaterinburg (GMT+05:00)', value: 'Asia/Yekaterinburg' },
      { text: 'Colombo (GMT+05:30)', value: 'Asia/Colombo' },
      { text: 'New Delhi (GMT+05:30)', value: 'Asia/New_Delhi' },
      { text: 'Almaty (GMT+06:00)', value: 'Asia/Almaty' },
      { text: 'Bishkek (GMT+06:00)', value: 'Asia/Bishkek' },
      { text: 'Dhaka (GMT+06:00)', value: 'Asia/Dhaka' },
      { text: 'Kashgar (GMT+06:00)', value: 'Asia/Kashgar' },
      { text: 'Novosibirsk (GMT+07:00)', value: 'Asia/Novosibirsk' },
      { text: 'Qyzylorda (GMT+06:00)', value: 'Asia/Qyzylorda' },
      { text: 'Bangkok (GMT+07:00)', value: 'Asia/Bangkok' },
      { text: 'Ho Chi Minh (GMT+07:00)', value: 'Asia/Ho_Chi_Minh' },
      { text: 'Jakarta (GMT+07:00)', value: 'Asia/Jakarta' },
      { text: 'Krasnoyarsk (GMT+07:00)', value: 'Asia/Krasnoyarsk' },
      { text: 'Phnom Penh (GMT+07:00)', value: 'Asia/Phnom_Penh' },
      { text: 'Chongqing (GMT+08:00)', value: 'Asia/Chongqing' },
      { text: 'Hong Kong (GMT+08:00)', value: 'Asia/Hong_Kong' },
      { text: 'Kuala Lumpur (GMT+08:00)', value: 'Asia/Kuala_Lumpur' },
      { text: 'Manila (GMT+08:00)', value: 'Asia/Manila' },
      { text: 'Shanghai (GMT+08:00)', value: 'Asia/Shanghai' },
      { text: 'Singapore (GMT+08:00)', value: 'Asia/Singapore' },
      { text: 'Taipei (GMT+08:00)', value: 'Asia/Taipei' },
      { text: 'Perth (GMT+08:00)', value: 'Australia/Perth' },
      { text: 'Ulaanbaatar (GMT+08:00)', value: 'Asia/Ulaanbaatar' },
      { text: 'Seoul (GMT+09:00)', value: 'Asia/Seoul' },
      { text: 'Tokyo (GMT+09:00)', value: 'Asia/Tokyo' },
      { text: 'Vladivostok (GMT+10:00)', value: 'Asia/Vladivostok' },
      { text: 'Port Moresby (GMT+10:00)', value: 'Pacific/Port_Moresby' },
      { text: 'Magadan (GMT+11:00)', value: 'Asia/Magadan' },
      { text: 'Canberra (GMT+11:00)', value: 'Australia/Canberra' },
      { text: 'Sydney (GMT+11:00)', value: 'Australia/Sydney' },
      { text: 'Noumea (GMT+11:00)', value: 'Pacific/Noumea' },
      { text: 'Fiji (GMT+12:00)', value: 'Pacific/Fiji' },
      { text: 'Auckland (GMT+13:00)', value: 'Pacific/Auckland' },
      { text: 'Apia (GMT+14:00)', value: 'Pacific/Apia' },
    ];
  }
}
