
// @NgModule({
//   declarations: [
//     AppComponent,
//     LoginComponent,
//     DashboardComponent,
//     WaitingComponent,
//     InputComponent,
//     SwitchComponent,
//     TagComponent,
//     RadioComponent,
//     DropdownComponent,
//     FormComponent,
//     FileComponent,
//     EditorComponent,
//     DatePickerComponent,
//     ZonePickerComponent,
//     CountryPickerComponent,
//     ColorPickerComponent,
//     CheckboxComponent,
//     ButtonComponent,
//     CalendarComponent,
//     BoxGridComponent,
//     AutoCompleteComponent,
//     DocViewerComponent,
//     EmojiPickerComponent,
//     MapComponent,
//     LocationPickerComponent,
//     ScheduleComponent,
//     ProgressComponent,
//     GridComponent,
//     TranslatePipe,
//     RegisterComponent,
//     ForgotComponent,
//     ValidationComponent,
//     OnlyNumberDirective,
//     HeaderComponent,
//     ProfileComponent,
//     FilesComponent,
//     TransactionsComponent,
//     PremiumPlansComponent,
//     CulturedDatePipe,
//     CulturedDateTimePipe,
//     MomentAgoPipe,
//     ConfirmComponent,
//     EnterToBrPipe,
//     QuickAccessComponent,
//     SearchResultComponent,
//     ConfirmAccountComponent,
//     StringFormatPipe,
//     PhoneVerificationComponent,
//     PromptComponent,
//     ChangePhoneComponent,
//     FileFolderPreviewComponent,
//     FilesExplorerComponent,
//     CtrlClickDirective,
//     DashboardEventsComponent,
//     DashboardOverallComponent,
//     DashboardProgressComponent,
//     DashboardActivityComponent,
//     DashboardProjectComponent,
//     DashboardProjectTemplatesComponent,
//     ProjectInfoComponent,
//     CreateWizardComponent,
//     InviteNewMemberComponent,
//     MemberInfoComponent,
//     MessengerComponent,
//     GroupComponent,
//     MessengerShortcutComponent,
//     ProjectComponent,
//     WorkPackageComponent,
//     SearchPipe,
//     EnumPipe,
//     MessengerSettingComponent,
//     ConversationComponent,
//     TasksComponent,
//     InitialsPipe,
//     OrgChartComponent,
//     GroupMembersComponent,
//     HumanResourcesComponent,
//     GroupReportsComponent,
//     GroupProjectsComponent,
//     GroupChartComponent,
//     OrgChartNodeComponent,
//     GroupInfoComponent,
//     ProjectInfoMiniComponent,
//     GroupTimespentComponent,
//     ChannelFilesComponent,
//     ProjectWizardComponent,
//     GroupWizardComponent,
//     ImportWizardComponent,
//     InviteGroupComponent,
//     InvitePeopleComponent,
//     TruncatePipe,
//     ProjectRoadMapComponent,
//     ProjectTreeComponent,
//     ProjectSeasonComponent,
//     ProjectObjectiveComponent,
//     ProjectSettingComponent,
//     AccessListComponent,
//     MsToDurationPipe,
//     ProjectTreeNodeComponent,
//     WorkPackageBoardComponent,
//     WorkPackageListComponent,
//     WorkPackageTimeSpanComponent,
//     WorkPackageCalendarComponent,
//     ChangeEmailComponent,
//     ReloadOnParamsChangedDirective,
//     GroupDetailComponent,
//     InviteModalComponent,
//     GroupNamePipe,
//     GroupSettingsComponent,
//     WorkPackageWizardComponent,
//     WorkPackageTaskComponent,
//     TaskModalComponent,
//     MapModalComponent,
//     EstimatedTimePipe,
//     ActivityLogComponent,
//     CustomFieldsComponent,
//     TimeSpanComponent,
//     NumberComponent,
//     TimePickerComponent,
//     DocumentModalComponent,
//     DevicesComponent,
//     InviteMemberComponent,
//     UpgradeWorkPackageComponent,
//     CalendarMonthComponent,
//     TimeSpentComponent,
//     KartablComponent,
//     DurationPickerComponent,
//     WorkPackagePermissionComponent,
//     ArchivedProjectsComponent,
//     ArchivedGroupsComponent,
//     LabelsModalComponent,
//     CustomFieldsModalComponent,
//     OfflineComponent,
//     FullNamePipe,
//     AdvancedPlayerComponent,
//     MemberFilterPipe,
//     TimeOffApproveModalComponent,
//     TimeOffHistoryModalComponent,
//     BulkDownloadModalComponent,
//     VideoComponent,
//     AudioComponent,
//     ThumbnailUrlPipe,
//     PersianDatePickerComponent,
//     NativeDatePickerComponent,
//     HijriDatePickerComponent,
//     NoApiFoundComponent,
//     NotFoundComponent,
//     NotAuthorizedComponent,
//   ],
//   entryComponents: [
//     TimeOffApproveModalComponent,
//     TimeOffHistoryModalComponent,
//     AdvancedPlayerComponent,
//     OfflineComponent,
//     CustomFieldsModalComponent,
//     LabelsModalComponent,
//     WorkPackagePermissionComponent,
//     UpgradeWorkPackageComponent,
//     DocumentModalComponent,
//     MapModalComponent,
//     WorkPackageWizardComponent,
//     ConfirmComponent,
//     PromptComponent,
//     ChangePhoneComponent,
//     CreateWizardComponent,
//     MessengerSettingComponent,
//     ChangeEmailComponent,
//     GroupDetailComponent,
//     InviteModalComponent,
//     TaskModalComponent,
//     BulkDownloadModalComponent,
//   ],
//   imports: [
//     MatNativeDateModule,
//     ClipboardModule,
//     BrowserModule,
//     AppRoutingModule,
//     BrowserAnimationsModule,
//     FormsModule,
//     HttpClientModule,
//     MatButtonModule,
//     MatToolbarModule,
//     MatTabsModule,
//     MatPaginatorModule,
//     MatTableModule,
//     MatMenuModule,
//     MatSnackBarModule,
//     SocketIoModule,
//     QuillModule.forRoot(),
//     SimpleModalModule.forRoot(
//       { container: 'modal-container' },
//       {
//         ...defaultSimpleModalOptions,
//         closeOnEscape: true,
//         closeOnClickOutside: true,
//         wrapperClass: 'in',
//         wrapperDefaultClasses: 'modal fade-anim',
//         bodyClass: 'modal-open',
//       },
//     ),
//     NgxPopperModule.forRoot({ placement: 'bottom' }),
//     RoundProgressModule,
//     BarChartModule,
//     MatRadioModule,
//     MatCheckboxModule,
//     MatProgressBarModule,
//     MatAutocompleteModule,
//     MatFormFieldModule,
//     ReactiveFormsModule,
//     MatRippleModule,
//     MomentModule,
//     ContentLoaderModule,
//     TrendModule,
//     DragDropModule,
//     ColorPickerModule,
//     NgxDocViewerModule,
//     ServiceWorkerModule.register('ngsw-worker.js', {
//       enabled: environment.production,
//     }),
//     MatSliderModule,
//     MatIconModule,
//     NgxAudioPlayerModule,
//     MatDatepickerModule,
//     NgxGoogleAnalyticsModule.forRoot(environment.ga),
//   ],
//   providers: [
//     GoogleAnalyticsService,
//     CookieService,
//     {
//       provide: HTTP_INTERCEPTORS,
//       useClass: HttpInterceptor,
//       multi: true,
//     },
//     {
//       provide: Socket,
//       useClass: PanelSocketProvider,
//     },
//     {
//       provide: APP_INITIALIZER,
//       useFactory: AppInitializerFactory,
//       deps: [AppInitializerProvider],
//       multi: true,
//     },
//     AppInitializerProvider,
//   ],
//   bootstrap: [AppComponent],
// })
// export class AppModule {}
